Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -48,15 +48,13 @@ runs:
           if [[ ! -z $result ]]; then
             found_string=true
             string_locations+="${file@Q}:\n${result@Q}\n\n"
-            echo "" && exit 1;
           fi
         done < changed_files.txt
 
         if [[ $found_string == true ]]; then
           # echo "::set-output name=found_string::true"
           # echo "::set-output name=string_locations::${string_locations@Q}"
-          echo "Issues Detected"
-          exit 1
+          echo "::error title=DO NOT MERGE::Issues Detected" && exit 1
         fi
 
       shell: bash
