Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -55,7 +55,8 @@ runs:
         if [[ $found_string == true ]]; then
           # echo "::set-output name=found_string::true"
           # echo "::set-output name=string_locations::${string_locations@Q}"
-          echo "::error::Issues Detected" && exit 1
+          echo "::error::Issues Detected"
+          exit 1
         fi
 
       shell: bash
