Array + Annotate

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -36,14 +36,24 @@ runs:
         found_string=false
         string_locations=""
         while read file; do
-          result=$(grep -n ".*${{ inputs.search_string }}.*" "$file" || true)
+          result=($(grep -n ".*${{ inputs.search_string }}.*" "$file" || true))
           echo "$result"
-          if [[ ! -z $result ]]; then
+          
+          if [[ ${#result[@]} -gt 0 ]]; then
             found_string=true
-            string_locations+="${file}:\n${result@Q}\n\n"
+            string_locations+="${file}:\n${result[*]@Q}\n\n"
+            for result in "${results[@]}"; do
+              line_number=$(echo "$result" | cut -d ':' -f 1)
+              line_content=$(echo "$result" | cut -d ':' -f 2-)
+              echo "::error file=${file},line=${line_number},title=DO NOT MERGE::${line_content}"
+            done
+            # result=$(grep -n ".*${{ inputs.search_string }}.*" "$file" || true)
+            # if [[ ! -z $result ]]; then
+            # found_string=true
+            # string_locations+="${file}:\n${result@Q}\n\n"
             # Annotate the file with the search results
             # echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
-            echo "::error file=${file},title=DO NOT MERGE::${result}"
+            # echo "::error file=${file},title=DO NOT MERGE::${result}"
           fi
         done < changed_files.txt
         echo "FOUND_STRING=$found_string" >> "$GITHUB_ENV"
